<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  '$_SERVER does not have {vars}.' => 'Переменная $_SERVER не содержит {vars}.',
  '$_SERVER variable' => 'Переменная $_SERVER.',
  '$_SERVER["SCRIPT_FILENAME"] must be the same as the entry script file path.' => 'Переменная $_SERVER["SCRIPT_FILENAME"] должна соответствовать пути к файлу входного скрипта.',
  'Either $_SERVER["REQUEST_URI"] or $_SERVER["QUERY_STRING"] must exist.' => 'Должна существовать хотя бы одна из серверных переменных: $_SERVER["REQUEST_URI"] или $_SERVER["QUERY_STRING"].',
  '{name} extension' => 'Расширение {name}',
  '{name} function' => 'Функция {name}',
  '{name} class' => 'Класс {name}',
  '{product} {min} or higher is required.' => 'Необходима версия {product} {min} и выше.',
  '{product} {max} or lower is required.' => 'Необходима версия {product} {max} и ниже.',
  '{product} {is} is required.' => 'Необходима версия {product} {min}.',
  '{product} {min} or higher or {max} or lower is required.' => 'Необходима версия {product} {min} и выше или {max} и ниже.',
  '{product} {min} or higher or {is} is required.' => 'Необходима версия {product} {min} и выше или {is}.',
  '{product} {max} or lower or {is} is required.' => 'Необходима версия {product} {max} и ниже или {is}.',
  '{product} {min} or higher or {max} or lower or {is} is required.' => 'Необходима версия {product} {min} и выше или {max} и ниже или {is}.',
  '{product} version' => 'Версия {product}',
  'This is required by encrypt and decrypt methods.' => 'Требуется для работы методов шифрования и дешифрации.',
  'This is required if you are using MySQL database.' => 'Требуется для работы с БД MySQL.',
  'This is required if you are using PostgreSQL database.' => 'Требуется для работы с БД PostgreSQL.',
  'This is required if you are using SQLite database.' => 'Требуется для работы с БД SQLite.',
  'Unable to determine URL path info. Please make sure $_SERVER["PATH_INFO"] (or $_SERVER["PHP_SELF"] and $_SERVER["SCRIPT_NAME"]) contains proper value.' => 'Не удалось получить информацию о пути. Пожалуйста, проверьте, содержится ли корректное значение в переменной $_SERVER["PATH_INFO"] (или $_SERVER["PHP_SELF"] и $_SERVER["SCRIPT_NAME"]).',
  'MySQL version'=>'Версия MySQL',
  'Folder {name} readable'=>'Доступность папки {name} для чтения',
  'Folder {name} writable'=>'Доступность папки {name} для записи',
  'File {name} readable'=>'Доступность файла {name} для чтения',
  'File {name} writable'=>'Доступность файла {name} для записи',
);
